image: Visual Studio 2019

environment:
  global:
    RANDOM_SEED: 12345
  matrix:
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 9

cache:
  - env

install:
  # Add Make and Python to the PATH
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%;%PATH%
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%\Scripts;%PATH%
  # Install system dependencies
  - curl -sSL https://install.python-poetry.org | python -
  - set PATH=%USERPROFILE%\AppData\Roaming\Python\Scripts;%PATH%
  - make doctor
  # Install project dependencies
  - make depends-ci

build: off

test_script:
  - make ci
